### PR TITLE
make pcap buffer size configurable

### PR DESCRIPTION
**Pull request by andreasheil**
* added a cmdline option -B which takes the buffer size in MB for pcap
* added config option capture.buffer for the same purpose
* implemented setting of pcap buffer size
* updated manpage and example config

was requested in #246, too

Greeting,
Andreas

### CODE REVIEW

**Comment by Kaian** [comment]
Hi @andreasheil 

Thanks a lot for the PR!

There is a commit mentioned in #246 (https://github.com/Kaian/sngrep/commit/648e7e687f1d3457713301300ebcae9fa76b4a10) that was not merged in the end that have better error checking during pcap activation.

Would be possible to merge both changes?

Also: if you `push -f` a branch related with a Pull Request, github will replace your old commits with new ones, so It's possible to change pull request commits anytime!

Thanks for your hard work!

**Comment by andreasheil** [comment]
Thanks,
I'll try to merge them.

**Comment by andreasheil** [comment]
Hi @Kaian,

according to the man pages (and source) the pcap_set functions only return with an error if they are called after pcap_activate(). But I think that can't happen in this scenario.

Greetings,
Andreas

**Comment by andreasheil** [comment]
sorry, clicked the wrong button... :-)

**Comment by Kaian** [comment]
It's ok to me then

I suggested to check them because the code already existed in another commit and other tools like tcpdump actually checks the return code. It also makes the code ready in case of the library changes its behaviour and starts returning some meaningful information.

Thanks!

**Comment by andreasheil** [comment]
I've pushed that.

**Comment by Kaian** [comment]
Awesome!

Thanks @andreasheil !

**Pull request merged**
