### PR TITLE
save: ability to save single SIP message

### PR DESCRIPTION
**Pull request by jmillan**
in Call Flow window, ability to save the current SIP message

### CODE REVIEW

**Comment by Kaian** [comment]
Hi @jmillan 

Thanks for digging again in the code for another PR! 

We can use some field attributes. According the [`man field_opts`](http://linux.die.net/man/3/field_opts) of ncurses, we can turn off the O_VISIBLE attribute of the field in the creation, and make it visible again in `save_set_msg`. Invisible fields are not considered for the form driver movements, so there is no need to add excetions in `save_handle_key`. If not visible we also remove the need to write `-` in the _radio button thing_

The field label is printed in `save_draw` function where you can check if info->msg has value in order to display it or not.

For pcap+rtp radio we've chosen to disable it instead of hidding because we want to show that saving rtp is possible but actual running mode does not allow it, but for this case I think hidding is better :)

Thanks a lot!!

**Comment by jmillan** [comment]
> We can use some field attributes. According the man field_opts of ncurses, we can turn off the O_VISIBLE attribute of the field in the creation, and make it visible again in save_set_msg. Invisible fields are not considered for the form driver movements, so there is no need to add excetions in save_handle_key. If not visible we also remove the need to write - in the radio button thing

That is what I was looking for ;-), thanks.

**Comment by Kaian** [comment]
Awesome!
Thanks José!!

**Comment by jmillan** [comment]
My pleasure ;-)

**Pull request merged**
