### PR TITLE
capture: add support for IPIP tunnel

### PR DESCRIPTION
**Pull request by zinid**
This resolves https://github.com/irontec/sngrep/issues/264

### CODE REVIEW

**Comment by Kaian** [comment]
Thanks for the contribution!

Can you provide a sample pcap for testing this? If it mixes non-ipip and ipip frames it would be even better.

Have you tried to save the generated packets into a different pcap? I'm a bit worried about changing the link layer info and packet content but no the header data that contains capture size for example.

Thanks in advance!

**Comment by zinid** [comment]
@Kaian I've added a pcap file and a new test case (011).

But you're right, produced PCAP is broken:
bad-ipip-pcap-output

I will look into this problem.

**Comment by zinid** [comment]
@Kaian I've re-done my patch: it's now much simpler and doesn't break output PCAP dump.

**Comment by Kaian** [comment]
Hi @zinid 

This looks simpler and also seems to work, although as you mention fragmentation in the outer layer is not yet supported.
I have manually merged the PR in https://github.com/irontec/sngrep/commit/f1492d8e41dd38965d3ee87c14f7a19f4649ab54 with a change in the while loop, because the no conditional infinite loop looks a bit scary.

    while (*size >= sizeof(struct ip))  {

instead of the while (1)


Thanks for your time and effort in this contribution!!

**Pull request closed without merging**
